# Generated by Django 5.1.6 on 2025-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_rename_user_id_heartrate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
